package cost


var baseCostListQuery = `
SELECT 
	A.ID,
	A.COST_CATEGORY_PARENT,
	COALESCE(A.COST_CATEGORY_CHILD, '') AS COST_CATEGORY_CHILD,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_COST_CATEGORY A
WHERE 1=1
`	

func buildCostListQuery() string {
	return baseCostListQuery + " AND A.FLAG_IS_DELETED = FALSE ORDER BY A.UPDATED_AT DESC"
}

func buildCostListRecycledQuery() string {
	return baseCostListQuery + " AND A.FLAG_IS_DELETED = TRUE ORDER BY A.UPDATED_AT DESC"
}

var baseCostExistsInRecycleBinQuery = `
SELECT EXISTS (
	SELECT 1
	FROM master_cost_category
	WHERE LOWER(cost_category_parent) = LOWER($1)
	AND LOWER(COALESCE(cost_category_child, '')) = LOWER(COALESCE($2, ''))
	AND flag_is_deleted = true
);
`

var baseCostInsert = `
INSERT INTO MASTER_COST_CATEGORY (
	COST_CATEGORY_PARENT,
	COST_CATEGORY_CHILD
) VALUES (
	$1,
	CASE
		WHEN TRIM($2) = '' THEN ''
		ELSE TRIM($2)
	END
)
`

var baseCostByIDQuery = `
SELECT 
	A.ID,
	A.COST_CATEGORY_PARENT,
	A.COST_CATEGORY_CHILD,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_COST_CATEGORY A
WHERE A.ID = $1 
`


var baseCostDelete = `
UPDATE MASTER_COST_CATEGORY
SET FLAG_IS_DELETED = TRUE, UPDATED_AT = NOW()
WHERE ID = $1
`

var baseCostUpdate = `
UPDATE MASTER_COST_CATEGORY
SET
	COST_CATEGORY_PARENT = $1,
	COST_CATEGORY_CHILD = $2,
	UPDATED_AT = NOW(),
	FLAG_IS_DELETED = false
WHERE ID = $3
`


var baseCostListNamesQuery = `
SELECT 
	CASE WHEN A.COST_CATEGORY_CHILD IS NULL THEN A.COST_CATEGORY_PARENT 
	ELSE CONCAT(A.COST_CATEGORY_PARENT, ' (', A.COST_CATEGORY_CHILD, ')') END AS COST_CATEGORY_NAME
FROM MASTER_COST_CATEGORY A
WHERE A.FLAG_IS_DELETED = FALSE
`

var baseCostNameLatestQuery = `
SELECT 
	CASE WHEN A.COST_CATEGORY_CHILD IS NULL THEN A.COST_CATEGORY_PARENT
	ELSE CONCAT(A.COST_CATEGORY_PARENT, ' (', A.COST_CATEGORY_CHILD, ')') END AS COST_CATEGORY_NAME
FROM MASTER_COST_CATEGORY A
WHERE A.FLAG_IS_DELETED = FALSE
ORDER BY A.CREATED_AT DESC
LIMIT 1
`