package event


var baseEventListQuery = `
SELECT 
	A.ID,
	A.EVENT_CATEGORY_PARENT,
	COALESCE(A.EVENT_CATEGORY_CHILD, '') AS EVENT_CATEGORY_CHILD,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_EVENT_CATEGORY A
WHERE 1=1
`	

func buildEventListQuery() string {
	return baseEventListQuery + " AND A.FLAG_IS_DELETED = FALSE"
}

func buildEventListRecycledQuery() string {
	return baseEventListQuery + " AND A.FLAG_IS_DELETED = TRUE"
}

var baseEventListNamesQuery = `
SELECT DISTINCT 
	A.EVENT_CATEGORY_PARENT
FROM MASTER_EVENT_CATEGORY A
WHERE A.FLAG_IS_DELETED = FALSE
ORDER BY A.EVENT_CATEGORY_PARENT
`


var baseEventInsert = `
INSERT INTO MASTER_EVENT_CATEGORY (
	EVENT_CATEGORY_PARENT,
	EVENT_CATEGORY_CHILD
) VALUES ($1, $2)

`

var baseEventByIDQuery = `
SELECT 
	A.ID,
	A.EVENT_CATEGORY_PARENT,
	COALESCE(A.EVENT_CATEGORY_CHILD, '') AS EVENT_CATEGORY_CHILD,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_EVENT_CATEGORY A
WHERE A.ID = $1 
`


var baseEventDelete = `
UPDATE MASTER_EVENT_CATEGORY
SET FLAG_IS_DELETED = TRUE, UPDATED_AT = NOW()
WHERE ID = $1
`

var baseEventUpdate = `
UPDATE MASTER_EVENT_CATEGORY
SET
	EVENT_CATEGORY_PARENT = $1,
	EVENT_CATEGORY_CHILD = $2,
	UPDATED_AT = NOW(),
	FLAG_IS_DELETED = false
WHERE ID = $3
`

