package event


var baseEventListQuery = `
SELECT 
	A.ID,
	A.EVENT_CATEGORY_PARENT,
	COALESCE(A.EVENT_CATEGORY_CHILD, '') AS EVENT_CATEGORY_CHILD,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_EVENT_CATEGORY A
WHERE 1=1
`	

func buildEventListQuery() string {
	return baseEventListQuery + " AND A.FLAG_IS_DELETED = FALSE"
}

func buildEventListRecycledQuery() string {
	return baseEventListQuery + " AND A.FLAG_IS_DELETED = TRUE"
}

var baseEventListNamesQuery = `
SELECT 
	CASE WHEN 
		A.EVENT_CATEGORY_CHILD IS NULL THEN A.EVENT_CATEGORY_PARENT 
		ELSE A.EVENT_CATEGORY_PARENT || ' (' || A.EVENT_CATEGORY_CHILD || ')' 
		END AS EVENT_CATEGORY_NAME
FROM MASTER_EVENT_CATEGORY A
WHERE A.FLAG_IS_DELETED = FALSE
ORDER BY A.EVENT_CATEGORY_PARENT
`


var baseEventInsert = `
INSERT INTO MASTER_EVENT_CATEGORY (
	EVENT_CATEGORY_PARENT,
	EVENT_CATEGORY_CHILD
) VALUES ($1, $2)
`

var baseEventActivityInsert = `
INSERT INTO USER_PROJECT_ACTIVITY (
	USER_ID,
	PROJECT_ID,
	ACTIVITY_TYPE,
	ACTIVITY_TITLE,
	ACTIVITY_BODY,
	ACTIVITY_DATE,
	EVENT_CATEGORY_ID,
	FLAG_IS_COMPLETED
) VALUES (
	(SELECT UUID FROM USER_AUTH WHERE EMAIL = $1 LIMIT 1),
	(SELECT ID FROM MASTER_PROJECT_LIST WHERE PROJECT_NAME = $2 AND FLAG_IS_DELETED = FALSE LIMIT 1),
	'event',
	$3,
	$4,
	$5,
	(SELECT ID FROM MASTER_EVENT_CATEGORY WHERE EVENT_CATEGORY_PARENT = $6 AND FLAG_IS_DELETED = FALSE LIMIT 1),
	$7
)
`
	

var baseEventByIDQuery = `
SELECT 
	A.ID,
	A.EVENT_CATEGORY_PARENT,
	COALESCE(A.EVENT_CATEGORY_CHILD, '') AS EVENT_CATEGORY_CHILD,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_EVENT_CATEGORY A
WHERE A.ID = $1 
`


var baseEventDelete = `
UPDATE MASTER_EVENT_CATEGORY
SET FLAG_IS_DELETED = TRUE, UPDATED_AT = NOW()
WHERE ID = $1
`

var baseEventUpdate = `
UPDATE MASTER_EVENT_CATEGORY
SET
	EVENT_CATEGORY_PARENT = $1,
	EVENT_CATEGORY_CHILD = $2,
	UPDATED_AT = NOW(),
	FLAG_IS_DELETED = false
WHERE ID = $3
`

