package project


var baseProjectListQuery = `
SELECT 
	A.ID,
	CONCAT(B.CUSTOMER_NAME_FIRST, ' ', B.CUSTOMER_NAME_LAST) AS CUSTOMER_NAME,
	A.PROJECT_NAME,
	COALESCE(TO_CHAR(A.PROJECT_START_DATE, 'YYYY-MM-DD'), '') AS PROJECT_START_DATE,
	COALESCE(TO_CHAR(A.PROJECT_END_DATE_EST, 'YYYY-MM-DD'), '') AS PROJECT_END_DATE_EST,
	COALESCE(TO_CHAR(A.PROJECT_END_DATE_ACTUAL, 'YYYY-MM-DD'), '') AS PROJECT_END_DATE_ACTUAL,
	ROUND(A.PROJECT_PRICE, 0)::int AS PROJECT_PRICE,
	ROUND(A.PROJECT_BUDGET, 0)::int AS PROJECT_BUDGET,
	A.PROJECT_NOTE,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_PROJECT_LIST A
LEFT JOIN MASTER_CUSTOMER_LIST B ON A.CUSTOMER_ID = B.ID
WHERE 1=1
`	

func buildProjectListQuery() string {
	return baseProjectListQuery + " AND A.FLAG_IS_DELETED = FALSE"
}

func buildProjectListRecycledQuery() string {
	return baseProjectListQuery + " AND A.FLAG_IS_DELETED = TRUE"
}


var baseProjectInsert = `
INSERT INTO MASTER_PROJECT_LIST (
	CUSTOMER_ID,
	PROJECT_NAME,
	PROJECT_START_DATE,
	PROJECT_END_DATE_EST,
	PROJECT_END_DATE_ACTUAL,
	PROJECT_PRICE,
	PROJECT_BUDGET,
	PROJECT_NOTE
) VALUES ((select id from master_customer_list where CONCAT(customer_name_first, ' ', customer_name_last) = $1), $2, $3, $4, $5, $6, $7, $8)
`

var baseProjectByIDQuery = `
SELECT 
	A.ID,
	CONCAT(B.CUSTOMER_NAME_FIRST, ' ', B.CUSTOMER_NAME_LAST) AS CUSTOMER_NAME,
	A.PROJECT_NAME,
	COALESCE(TO_CHAR(A.PROJECT_START_DATE, 'YYYY-MM-DD'), '') AS PROJECT_START_DATE,
	COALESCE(TO_CHAR(A.PROJECT_END_DATE_EST, 'YYYY-MM-DD'), '') AS PROJECT_END_DATE_EST,
	COALESCE(TO_CHAR(A.PROJECT_END_DATE_ACTUAL, 'YYYY-MM-DD'), '') AS PROJECT_END_DATE_ACTUAL,
	A.PROJECT_PRICE,
	A.PROJECT_BUDGET,
	A.PROJECT_NOTE,
	A.FLAG_IS_DELETED,
	A.CREATED_AT,
	A.UPDATED_AT
FROM MASTER_PROJECT_LIST A
LEFT JOIN MASTER_CUSTOMER_LIST B ON A.CUSTOMER_ID = B.ID
WHERE A.ID = $1 
`


var baseProjectDelete = `
UPDATE MASTER_PROJECT_LIST
SET FLAG_IS_DELETED = TRUE, UPDATED_AT = NOW()
WHERE ID = $1
`

var baseProjectUpdate = `
UPDATE MASTER_PROJECT_LIST
SET
	CUSTOMER_ID = (select id from master_customer_list where CONCAT(customer_name_first, ' ', customer_name_last) = $1),
	PROJECT_NAME = $2,
	PROJECT_START_DATE = $3,
	PROJECT_END_DATE_EST = $4,
	PROJECT_END_DATE_ACTUAL = $5,
	PROJECT_PRICE = $6,
	PROJECT_BUDGET = $7,
	PROJECT_NOTE = $8,
	UPDATED_AT = NOW(),
	FLAG_IS_DELETED = false
WHERE ID = $9
`
