package project


var baseProjectListQuery = `
SELECT 
	ID,
	CUSTOMER_ID,
	PROJECT_NAME,
	COALESCE(TO_CHAR(PROJECT_START_DATE, 'YYYY-MM-DD'), '') AS PROJECT_START_DATE,
	COALESCE(TO_CHAR(PROJECT_END_DATE_EST, 'YYYY-MM-DD'), '') AS PROJECT_END_DATE_EST,
	COALESCE(TO_CHAR(PROJECT_END_DATE_ACTUAL, 'YYYY-MM-DD'), '') AS PROJECT_END_DATE_ACTUAL,
	FLAG_IS_DELETED,
	CREATED_AT,
	UPDATED_AT
FROM MASTER_PROJECT_LIST
WHERE FLAG_IS_DELETED = FALSE
`	


var baseProjectInsert = `
INSERT INTO MASTER_PROJECT_LIST (
	CUSTOMER_ID,
	PROJECT_NAME,
	PROJECT_START_DATE,
	PROJECT_END_DATE_EST,
	PROJECT_END_DATE_ACTUAL
) VALUES ((select id from master_customer_list where CONCAT(customer_name_first, ' ', customer_name_last) = $1), $2, $3, $4, $5)
`
