CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Enable UUID and crypto extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS USER_AUTH (
    UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EMAIL TEXT UNIQUE NOT NULL,
    GOOGLE_SUB TEXT UNIQUE, -- Google user ID
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);