CREATE TABLE IF NOT EXISTS MASTER_VENDOR_LIST (
    ID SERIAL PRIMARY KEY,
    VENDOR_NAME TEXT NOT NULL,
    VENDOR_PHONE TEXT,
    VENDOR_EMAIL TEXT,
    VENDOR_ADDRESS TEXT,
    COMMENT TEXT,
    FLAG_IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);