CREATE TABLE IF NOT EXISTS USER_AUTH_APPROVED_EMAIL (
    EMAIL TEXT PRIMARY KEY,
    IS_ADMIN BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO USER_AUTH_APPROVED_EMAIL (EMAIL, IS_ADMIN) VALUES
('SYSRONNIE@GMAIL.COM', true);