CREATE TABLE IF NOT EXISTS MASTER_COST_CATEGORY (
    ID SERIAL PRIMARY KEY,
    COST_CATEGORY_PARENT TEXT UNIQUE NOT NULL,
    COST_CATEGORY_CHILD TEXT UNIQUE NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
)