CREATE TABLE IF NOT EXISTS MASTER_REVENUE_CATEGORY (
    ID SERIAL PRIMARY KEY,
    REVENUE_CATEGORY_PARENT TEXT UNIQUE NOT NULL,
    REVENUE_CATEGORY_CHILD TEXT UNIQUE NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);