CREATE TABLE IF NOT EXISTS USER_PROJECT_ACTIVITY (
    ID SERIAL PRIMARY KEY,
    USER_ID UUID NOT NULL REFERENCES USER_AUTH(UUID),
    PROJECT_ID INT NOT NULL REFERENCES MASTER_PROJECT_LIST(ID),

    ACTIVITY_TYPE TEXT NOT NULL,
    ACTIVITY_TITLE TEXT NOT NULL,
    ACTIVITY_BODY TEXT,

    AMOUNT NUMERIC(12, 2),
    ACTIVITY_DATE DATE,

    EVENT_CATEGORY_ID INT REFERENCES MASTER_EVENT_CATEGORY(ID),
    COST_CATEGORY_ID INT REFERENCES MASTER_COST_CATEGORY(ID),
    VENDOR_ID INT REFERENCES MASTER_VENDOR_LIST(ID),

    PHOTO_URL TEXT,
    PHOTO_THUMBNAIL_URL TEXT,

    FLAG_IS_COMPLETED BOOLEAN DEFAULT FALSE,
    FLAG_IS_DELETED BOOLEAN DEFAULT FALSE,

    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),

    CHECK (
        ACTIVITY_TYPE IN (
            'event',
            'expense',
            'income',
            'note',
            'photo'
        )
    )
);