CREATE TABLE IF NOT EXISTS MASTER_PROJECT_LIST (
    ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL REFERENCES MASTER_CUSTOMER_LIST(ID),
    PROJECT_NAME TEXT NOT NULL,
    PROJECT_START_DATE DATE,
    PROJECT_END_DATE_EST DATE,
    PROJECT_END_DATE_ACTUAL DATE,
    FLAG_IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);