

-- Create user_auth_session table
CREATE TABLE IF NOT EXISTS USER_AUTH_SESSION (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID UUID NOT NULL REFERENCES USER_AUTH(UUID) ON DELETE CASCADE,
    SESSION_ID UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    REFRESH_TOKEN_HASH TEXT NOT NULL UNIQUE,
    USER_AGENT TEXT,
    IP_ADDRESS INET,
    CREATED_AT TIMESTAMPTZ DEFAULT now(),
    UPDATED_AT TIMESTAMPTZ DEFAULT now(),
    LAST_USED_AT TIMESTAMPTZ DEFAULT now(),
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    REVOKED_AT TIMESTAMPTZ,
    REVOKED_REASON TEXT
);
