CREATE TABLE IF NOT EXISTS MASTER_INCOME_CATEGORY (
    ID SERIAL PRIMARY KEY,
    INCOME_CATEGORY_PARENT TEXT NOT NULL,
    INCOME_CATEGORY_CHILD TEXT,
    FLAG_IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (INCOME_CATEGORY_PARENT, INCOME_CATEGORY_CHILD)
);


INSERT INTO MASTER_INCOME_CATEGORY
(INCOME_CATEGORY_PARENT, INCOME_CATEGORY_CHILD)
VALUES
('Bank Draw', NULL),
('Cash', NULL),
('Service', NULL),
('Home Sale', NULL),
('Lot Sale', NULL),
('Rental', NULL),
('Consulting', NULL),
('Other', NULL);