CREATE TABLE IF NOT EXISTS MASTER_VENDOR_LIST (
    ID SERIAL PRIMARY KEY,
    VENDOR_NAME TEXT NOT NULL,
    VENDOR_PRIMARY_CONTACT TEXT,
    VENDOR_PHONE TEXT,
    VENDOR_EMAIL TEXT,
    VENDOR_ADDRESS_STREET TEXT,
    VENDOR_ADDRESS_UNIT TEXT,
    VENDOR_ADDRESS_CITY TEXT,
    VENDOR_ADDRESS_STATE TEXT,
    VENDOR_ADDRESS_ZIP TEXT,
    COMMENT TEXT,
    FLAG_IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(VENDOR_NAME)
);