CREATE TABLE IF NOT EXISTS master_customer_list (
    ID SERIAL PRIMARY KEY,
    CUSTOMER_NAME_FIRST TEXT NOT NULL,
    CUSTOMER_NAME_LAST TEXT NOT NULL,
    CUSTOMER_PHONE TEXT,
    CUSTOMER_EMAIL TEXT,
    CUSTOMER_ADDRESS_STREET TEXT,
    CUSTOMER_ADDRESS_UNIT TEXT,
    CUSTOMER_ADDRESS_CITY TEXT,
    CUSTOMER_ADDRESS_STATE TEXT,
    CUSTOMER_ADDRESS_ZIP TEXT,
    COMMENT TEXT,
    FLAG_IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(CUSTOMER_NAME_FIRST, CUSTOMER_NAME_LAST)
);