// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package expense

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type Column struct {
	Key   string
	Label string
}

type ExpenseTableModel struct {
	Columns []Column
	Rows    []map[string]string
}

type ExpenseTableProps struct {
	ViewType ExpenseViewType
	Model    ExpenseTableModel
}

// Column{Key: "Name",Label: "Name",}
func ExpenseTable(props ExpenseTableProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(props.Model.Rows) > 0 {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"border rounded-lg p-4\"><div x-data=\"{ showActions: false }\" class=\"w-full\"><div id=\"modal-root\"></div><div class=\"flex justify-end mb-3\"><button @click=\"showActions = !showActions\" class=\"inline-flex items-center gap-2 px-3 py-1.5 text-sm font-medium \n                border rounded-md shadow-sm transition\" :class=\"showActions \n                ? &#39;bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100&#39; \n                : &#39;bg-gray-50 text-gray-600 border-gray-200 hover:bg-gray-100&#39;\"><img :src=\"showActions \n                    ? &#39;/public/svg/eye_closed_blue.svg&#39; \n                    : &#39;/public/svg/eye_open_grey.svg&#39;\" class=\"w-4 h-4 cursor-pointer\"> <span x-text=\"showActions ? &#39;Hide Actions&#39; : &#39;Show Actions&#39;\"></span></button></div><!-- SCROLL CONTAINER --><div class=\"max-h-[500px] overflow-y-auto overflow-x-auto\"><table class=\"min-w-full divide-y divide-gray-200\"><!-- HEADER --><thead class=\"bg-gray-50 sticky top-0 z-10\"><tr>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, column := range props.Model.Columns {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider bg-gray-50\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var2 string
				templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(column.Label)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `client/feature/expense/expense_table.templ`, Line: 58, Col: 46}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</th>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<th x-show=\"showActions\" class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider bg-gray-50\">Actions</th></tr></thead><!-- BODY --><tbody class=\"bg-white divide-y divide-gray-200\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, row := range props.Model.Rows {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, column := range props.Model.Columns {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-900\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var3 string
					templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(row[column.Key])
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `client/feature/expense/expense_table.templ`, Line: 77, Col: 53}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<td x-show=\"showActions\" class=\"px-6 py-4 whitespace-nowrap text-sm flex gap-3\"><button hx-get=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("/expense/modal-edit-record/" + string(props.ViewType) + "/" + row["id"])
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `client/feature/expense/expense_table.templ`, Line: 86, Col: 116}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-target=\"#modal-root\" hx-swap=\"innerHTML\" class=\"flex items-center gap-1 text-blue-600 hover:text-blue-800\"><img src=\"/public/svg/edit_blue.svg\" class=\"w-5 h-5\"> <span class=\"text-xs\">Edit</span></button> <button hx-get=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("/expense/modal-remove-record/" + string(props.ViewType) + "/" + row["id"])
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `client/feature/expense/expense_table.templ`, Line: 96, Col: 118}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-target=\"#modal-root\" hx-swap=\"innerHTML\" class=\"flex items-center gap-1 text-red-600 hover:text-red-800\"><img src=\"/public/svg/delete_red.svg\" class=\"w-5 h-5\"> <span class=\"text-xs\">Delete</span></button></td></tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</tbody></table></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
