// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package expense

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type ExpenseViewType string

const (
	ViewTypeClient   ExpenseViewType = "client"
	ViewTypeVendor   ExpenseViewType = "vendor"
	ViewTypeProject  ExpenseViewType = "project"
	ViewTypeCategory ExpenseViewType = "category"
	ViewTypeExpense  ExpenseViewType = "expense"
)

func ParseViewType(s string) (ExpenseViewType, bool) {
	switch s {
	case string(ViewTypeClient):
		return ViewTypeClient, true
	case string(ViewTypeProject):
		return ViewTypeProject, true
	case string(ViewTypeVendor):
		return ViewTypeVendor, true
	case string(ViewTypeCategory):
		return ViewTypeCategory, true
	case string(ViewTypeExpense):
		return ViewTypeExpense, true
	default:
		return "", false
	}
}

type ExpenseFormProps struct {
	ViewType ExpenseViewType
}

type ExpenseFormModelClient struct {
	Name    string
	Email   string
	Phone   string
	Address string
}

func ExpenseForm(props ExpenseFormProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.JSONScript("props", props).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/public/javascript/expense/expense_form.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.ViewType == ViewTypeClient {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"expense-form\" class=\"w-full max-w-5xl space-y-3\" hx-post=\"/expense/insert-new-record\" hx-target=\"#server-response-container\" hx-swap=\"innerHTML\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for index := range 5 {
				templ_7745c5c3_Err = ExpenseInputList(ExpenseInputProps{
					Id:       index,
					ViewType: props.ViewType,
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Actions --><div class=\"flex flex-row justify-end pt-2\"><div id=\"server-response-container\"></div><button type=\"submit\" class=\"btn btn-primary\">Save Client</button></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
